### ISSUE TITLE
[INVAILD] levelsys console spam

### ISSUE THREAD

**Issue by QuirkyDevil** [KumosLab/Discord-Levels-Bot#9]
In levelsys.py,   _async def on_message(self, ctx):_ 
on_message only takes 'message', 
It will spam console with `TypeError: on_message() missing 1 required positional argument: 'message'`

Not much of a problem with that but console spam will be very much
I would suggest to replace ctx with message
ctx.guild.id    >      message.guild.id
ctx.author    >      message.author
ctx.author.id    >      message.author.id
ctx.author.avatar_url    >      message.author.avatar_url

**Comment by KumosLab** [comment]
Hey there,

I've never noticed this, i've only just heard about this now. I was aware of previous console "spam" from if a user sent a dm to the bot (didn't spam, just sent an error every time).

I'll look into this later when I have spare time, sorry about the inconvenience, this is the first time i'm hearing about this.

Have a great day/night!

**Comment by QuirkyDevil** [comment]
Oh great! 
Take your time to solve it.
Have a wonderful day!/nighty night
